### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by guibranco** [GuilhermeStracini/apiclient-boilerplate-dotnet#255]
### GitHub Issue: Add `Directory.Build.props` to the Template Repository

**Feature Request**

To enhance the template repository **apiclient-boilerplate-dotnet**, I propose adding a `Directory.Build.props` file with the following contents:

```xml
<Project>
  <PropertyGroup Label="SDK Versions">
    <DotNetVersions>netstandard2.0;netstandard2.1;net6.0;net8.0</DotNetVersions>
    <DotNetVersionTests>net8.0</DotNetVersionTests>
  </PropertyGroup>
  
  <PropertyGroup Label="NuGet package">
    <Authors>Placeholder</Authors>
    <Company>Placeholder</Company>
    <Copyright>© $([System.DateTime]::Now.Year) Placeholderi. All rights reserved.</Copyright>
    <PackageProjectUrl>https://{{username}}.github.io/{{repository}}</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/{{username}}/{{reposiitory}}</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>

  <PropertyGroup Label="Build">
    <UpdateVersionProperties>true</UpdateVersionProperties>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disabled</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <NoWarn>$(NoWarn);1591;NU5105;SA1633;CA1711</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Label="Analysis settings">
    <AnalysisLevel>latest-Recommended</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" Condition="$(MSBuildProjectExtension) == '.csproj' And $(IsTestProject) != 'true'" />
    <PackageReference Include="SonarAnalyzer.CSharp" PrivateAssets="all" Condition="$(MSBuildProjectExtension) == '.csproj' And $(IsTestProject) != 'true'" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\logo.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
```

### Benefits

1. **Centralized Configuration**: Ensures all projects in the repository follow consistent settings.
2. **Standardized NuGet Packaging**: Automates common properties for NuGet packages.
3. **Improved Build Settings**: Applies best practices for .NET builds and analysis.
4. **Simplified Multi-Targeting**: Facilitates support for multiple .NET versions.

### Tasks

- [ ] Add the `Directory.Build.props` file to the repository's root directory.
- [ ] Test the configuration in AppVeyor CI to verify compatibility with existing workflows.
- [ ] Update the repository documentation to include details about the `Directory.Build.props`.

By including this file, the template will provide a more robust starting point for .NET API client projects.
