### ISSUE TITLE
[FEATURE] Enable centralized package management in the template repository

### ISSUE THREAD

**Issue by guibranco** [GuilhermeStracini/apiclient-boilerplate-dotnet#256]
To improve package management consistency across projects in the **apiclient-boilerplate-dotnet** repository, I propose enabling **Centralized Package Management**. This feature simplifies the process of managing NuGet package versions by defining them in a single `Directory.Packages.props` file.

### Suggested Implementation

1. **Use the `central-pkg-converter` Tool**:  
   To streamline the transition to centralized package management, leverage the [`central-pkg-converter`](https://github.com/Webreaper/CentralisedPackageConverter). This tool automates the process of migrating existing `.csproj` files to use a `Directory.Packages.props` file.

   Command:
   ```bash
   central-pkg-converter /path/to/project-or-solution
   ```

2. Review and adjust the generated `Directory.Packages.props` file to ensure consistency and correctness.

3. Configure the build system (e.g., AppVeyor CI) to support Centralized Package Management.

### Example `Directory.Packages.props` File

```xml
<Project>
  <ItemGroup>
    <!-- Example packages -->
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="FluentAssertions" Version="6.11.0" />
    <PackageVersion Include="xunit" Version="2.4.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.5" />
  </ItemGroup>
</Project>
```

### Benefits

- **Consistency**: Ensures all projects use the same package versions.
- **Simplified Updates**: Makes it easier to update or pin package versions across the entire repository.
- **Reduced Duplication**: Eliminates the need to repeat version numbers in multiple project files.
- **Automation**: Speeds up the migration process using `central-pkg-converter`.

### Tasks

- [ ] Install the `central-pkg-converter` tool.
- [ ] Run the tool against the repository:
  ```bash
  central-pkg-converter /path/to/project-or-solution
  ```
- [ ] Review and refine the generated `Directory.Packages.props` file.
- [ ] Test the configuration locally and in the CI pipeline.
- [ ] Update the repository documentation to include details about Centralized Package Management.

By adopting centralized package management and automating the migration, we can ensure a smooth transition while reducing maintenance overhead.
